#!/bin/bash
source /nfs/users/nfs_r/rg12/lustre110/Pipeline/Sailfish/software/.bashrc;

while getopts “p:f:s:b:t:m:n:” OPTION
do
    case $OPTION in
        p)
		pairedend=$OPTARG
		;;
	f)
		fastq=$OPTARG
		;;
	s)
            	sailfish=$OPTARG
            	;;
        b)
            	strain=$OPTARG
            	;;
        t)
            	transcriptome=$OPTARG
            	;;
        m)
            	mate1=$OPTARG
            	;;
	n)
		mate2=$OPTARG
    esac
done


if [ $pairedend == "TRUE" ];
    then
    if [ $fastq == "FALSE" ];then
        salmon --no-version-check quant -p 32 -i $sailfish/Indexes/$strain/transcriptome/ -o $transcriptome -e -l "T=PE:O=><:S=U" -1 <(gunzip -cf $mate1) -2 <(gunzip -cf $mate2) --biasCorrect ;
    	status=$?;
    else
        salmon --no-version-check quant -p 12 -i $sailfish/Indexes/$strain/transcriptome/ -o $transcriptome -l "T=PE:O=><:S=U" -1 <(gunzip -cf $mate1) -2 <(gunzip -cf $mate2);
    	status=$?;
    fi
else
    salmon --no-version-check quant -p 12 -i $sailfish/Indexes/$strain/transcriptome/ -o $transcriptome -l "T=SE:S=U" -r <(gunzip -cf $mate1);
    status=$?;
fi
exit $status;
